### ISSUE TITLE
set up your Kanban board

### ISSUE THREAD

**Issue by hafiz1379** [hafiz1379/Recipe-app#20]
**This is the setup of our work**
You can find the GitHub project: https://github.com/users/hafiz1379/projects/7

**There** are 2people in this group:

- [ ] https://github.com/hafiz1379
- [ ] https://github.com/StarMindz

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi @hafiz1379 and @StarMindz,

#### While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

#### Your Code Review Request is marked as invalid for this reason:

- [ ] The link you provided for the project cards is broken. Please provide a valid link.

![image](https://github.com/hafiz1379/Recipe-app/assets/68796232/20c2907d-e167-4c52-9965-88f8ad4da6c3)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by hafiz1379** [comment]
@Omar-Muhamad Hi
But it's working correctly 
![image](https://github.com/hafiz1379/Recipe-app/assets/117447018/47be5027-20d3-406a-a845-d22defc688ab)

**Comment by tresorsawasawa** [comment]
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @hafiz1379 and @StarMindz 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All requirements have cards :heavy_check_mark: 
- Cards are divided  a fair way :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
